version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Skipping build step, no build required
  post_build:
    commands:
      - echo Creating deployment package...
      - zip -r app.zip * .[^.]*

artifacts:
  files:
    - app.zip
